Feat: Add user authentication related (jwt, jwt-refresh) features usi…
mash-up-kr/proof_Backend_Node pull request #13
Opened 2022-07-17 13:54 UTC by sumin21

# 개요
사용자가 카카오 로그인으로 로그인을 하면, Access token과 Refresh token을 생성하여 user 정보와 함께 클라이언트로 전송합니다.
# 작업 사항
## JwtGuard
요청이 왔을 때, 요청 헤더에서 Access token을 가져와 인증을 하고 인증이 성공하면 사용자 정보를 return한다. (임시로 사용자 정보를 return하게 구현했습니다.)
## JwtRefreshGuard
Access token 이 만료되었을 때, auth/token-refresh 로 요청이 오면 Refresh token으로 Access token을 재발급하여 반환합니다.
# 논의하고 싶은 점
- Access token이 만료되었다면 401 이외의 다른 특별한? 에러를 반환해야 할까요? (현재는 401이에요!)
- refresh token을 bcrypt로 암호화하여 user db에 저장했는데, 어디서 쓰일 데가 있을까요? 필요없으면 삭제해야 할까 싶어서용
- 최대한 user와 auth를 구분해보았는데 어색한 부분 있으면 말씀해주세요!

(최신 코드로 merge 완료했습니다)
(env 파일에 수정사항이 있어서 따로 채팅방에 올릴게요!)

2022-07-18 17:29 UTC, Marades requested changes

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.controller.ts
> +		console.log(user);
console.log 지우기!

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.controller.ts
> +		console.log(userData.user);
여기두용~

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.service.ts
> +	jwtConfig = this.configService.get<JwtConfig>('jwtConfig');
config들은 private필드로 선언하면 어떨까용??
ES2019부터 Class내에서 필드명 앞에 `#jwtConfig` 이런 식으로 `#`을 붙이면 private필드로 선언되는 걸로 알고 있습니다ㅎㅎ

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.service.ts
> +		});
함수의 인자로 user를 받고 refreshToken만 업데이트하는데 user를 다시 가져와야할 필요가 있을까용?

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.service.ts
> +	async getUserIfRefreshTokenMatches(id: string) {
함수명은 `getUserIfRefreshTokenMatches`인데 기능은 id를 받아서 그 id인 user가 있으면 반환만 해주고 있는 거 같아요~
함수명만 봐서는 refresh token이 일치하는 로직이 들어가야하지 않을까 싶습니당

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/auth.service.ts
> +	async removeRefreshToken(id: string) {
요 부분은 로그아웃 용으로 미리 만들어두신 부분인거죠?

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/strategies/jwt-refresh.strategy.ts
> +			IgnoreExpiration: false,
토큰 검증을 passport strategy에 위임하고 있지만 추후 클라분과의 소통을 위해 만료된 혹은 유효하지 않은 토큰일 때 response혹은 http status code가 어떻게 되는지 알아두면 좋을 거 같아용(저도 알려주세요ㅎㅎ)

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/strategies/jwt.strategy.ts
> +		return { id: payload.userId };
`authService.getUserIfRefreshTokenMatches`는 `{ userId: number }` 형식의 리턴인데 여기는 `{ id: number }` 형식의 리턴이네용ㅎㅎ 통일해두면 좋을 거 같아용
req.user에 담기게 될테니 id로 통일하면 될 거 같은데 어떨까요?!
#

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/interfaces/auth.interface.ts
> +export interface TokenSchema {
일종의 DTO역할을 해주는 인터페이스 같은데 dto의 용도라면 interface는 런타임 중 참조가 불가능하기 때문에(interface는 ts문법이여서 js로 변환 시 사라짐) class로 선언하는 걸 권장하고 있다고 합니당

Ref : https://docs.nestjs.com/controllers#request-payloads

2022-07-18 17:29 UTC, Marades commented on apps/api-server/src/auth/entities/users.entity.ts
> +export class User extends CommonEntity {
user entity 위치 옮겨졌는데 database.config.ts에서는 경로 안바뀐 거 같아용~

2022-07-19 16:11 UTC, sumin21 commented on apps/api-server/src/auth/auth.service.ts
> +	jwtConfig = this.configService.get<JwtConfig>('jwtConfig');
넵!

2022-07-19 16:12 UTC, sumin21 commented on apps/api-server/src/auth/auth.service.ts
> +		});
refresh token도 따로 반환되니까 한번더 받아올 필요가 없겠네요! 수정하겠습니다.

2022-07-19 16:13 UTC, sumin21 commented on apps/api-server/src/auth/auth.service.ts
> +	async getUserIfRefreshTokenMatches(id: string) {
passport-jwt가 token이 일치하는지 직접 검증하니까 필요가 없을 것 같습니다! 함수명을 수정하도록 할게요!

2022-07-19 16:14 UTC, sumin21 commented on apps/api-server/src/auth/auth.service.ts
> +	async removeRefreshToken(id: string) {
넵 맞아요.

2022-07-19 16:15 UTC, sumin21 commented on apps/api-server/src/auth/strategies/jwt-refresh.strategy.ts
> +			IgnoreExpiration: false,
아 네네 좋은 것 같아요. 상황에 따라 다르게 에러 메시지를 보내게 수정해보겠습니다.

2022-07-19 16:15 UTC, sumin21 commented on apps/api-server/src/auth/strategies/jwt.strategy.ts
> +		return { id: payload.userId };
id로 통일할게요!

2022-07-19 16:15 UTC, sumin21 commented on apps/api-server/src/interfaces/auth.interface.ts
> +export interface TokenSchema {
넵 그럼 dto class로 선언하겠습니다.

2022-07-19 16:15 UTC, sumin21 commented on apps/api-server/src/auth/entities/users.entity.ts
> +export class User extends CommonEntity {
앗 수정하겠습니다!

2022-07-19 16:44 UTC, sumin21 commented
refresh token으로 access token을 재발급 할 때,
- **refresh token이 정상 (유효)**
새로운 access token을 발급하여 응답 메시지로 전송

- **refresh token이 없거나, 유효하지 않은 경우**
401의 에러 코드 전송 (message: Unauthorized)
- **refresh token이 만료된 경우**
401의 에러 코드 전송 (message: token expired, error: Unauthorized)

2022-07-19 17:19 UTC, Marades approved these changes
auth부분이 처음 하기에 개념도 어렵고 헷갈리는 부분이 많은데 수고 많으셨습니다!

2022-07-20 14:17 UTC, merged