Feat: Add delete user api
mash-up-kr/proof_Backend_Node pull request #18
Opened 2022-08-02 12:59 UTC by sumin21

- 유저 탈퇴 api를 만들었습니다.
  - req : curl -X DELETE "http://localhost:3000/auth/users" -H "Authorization: Bearer 액세스키"
  - service : db에서 해당 사용자를 삭제합니다.
 
- 나중에 추가되는 기능에 따라 유저 탈퇴 service에도 추가되어야 할 기능들이 있을 것 같은데, 그건 추후에 확장하면 될 것 같습니다.
- main.ts에 주석 제거

2022-08-05 14:11 UTC, Gracechung-sw commented on apps/api-server/src/modules/auth/auth.service.ts
>  	}
그 CommonEntity보면 delete를 이렇게 하는게 어떨까 했는데, 어떻게 생각해??
보통 데이터는 좀 소중해서 바로 아에 삭제는 잘 안하는거 같던데 탈퇴같은거는 개인정보라던지 그런 문제때문에 아에 지워야 하나?? 이건 잘 모르겠어 @Marades 혹시 알려줄수 있어?

```
	// Soft Delete (기존에는 null, 삭제시에 timestamp를 찍는다.)
	// XXX: Need to discuss delete policy.
	@Exclude()
	@DeleteDateColumn({ type: 'timestamptz' })
	deletedAt?: Date | null;
```

2022-08-05 14:43 UTC, sumin21 commented on apps/api-server/src/modules/auth/auth.service.ts
>  	}
엇 그러게 이생각은 못해봤네..

2022-08-07 10:45 UTC, sumin21 commented on apps/api-server/src/database/seeds/users.seed.ts
> +			'https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_beer.png';
우선 이 png를 기본 프로필 이미지로 가정하였는데, config화 하는게 좋을까요??

2022-08-07 14:39 UTC, Marades commented on apps/api-server/src/modules/auth/auth.service.ts
>  	}
그 약관 같은 곳에 몇개월 간은 보관 이런 거 있긴 하던데 우린 걍 날리는 대신 연관 테이블 외래키 설정 SET NULL로 해서 데이터는 남게끔 하거나 하는 식으로 간단하게 처리해둬도 될 거 같긴 한디..어땡??

2022-08-07 14:41 UTC, Marades commented on apps/api-server/src/database/seeds/users.seed.ts
> +			'https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_beer.png';
유저가 새로 가입했을 때 기본으로 설정되어있어어야하니까 `user.constant.ts`같은 곳에 정의해둬도 괜찮지 않을까 싶기는 합니당

2022-08-09 09:42 UTC, sumin21 commented on apps/api-server/src/modules/auth/auth.service.ts
>  	}
내가 이해를 제대로 한건지 모르겠는데, 삭제한 유저를 참조하고 있는 다른 테이블(예를 들면, 리뷰 테이블)의 fk값을 null로 설정하는 식인걸까??

2022-08-09 10:24 UTC, sumin21 commented on apps/api-server/src/database/seeds/users.seed.ts
> +			'https://zuzu-resource.s3.ap-northeast-2.amazonaws.com/drinks-category/category_beer.png';
넵 그렇게 수정하겠습니당

2022-08-10 18:49 UTC, Marades approved these changes
response객체를 만들기 위해 delete쓰는 것도 좋지만 ResponseDTO를 따로 두는 방법도 고려해봅면 좋을 거 같아요~

2022-08-10 18:53 UTC, Marades requested changes
업데이트할 때 둘 다 필수값으로 두는 게 아니라 둘 중 하나의 값만 받을 수 있게 하는 게 좋을 거 같아요~!!

2022-08-11 17:25 UTC, sumin21 commented
요청하신 부분들 모두 수정 완료했습니다! 확인해주시면 감사해용

2022-08-12 02:50 UTC, Gracechung-sw approved these changes
수고하셨습니다~

2022-08-12 06:12 UTC, Marades approved these changes
수고하셨ㅅ브니다!

2022-08-12 06:12 UTC, merged