Chore: Change node package manger pnpm from npm
mash-up-kr/proof_Backend_Node pull request #6
Opened 2022-06-25 14:34 UTC by Marades

- change package manager
- update dockerfile

2022-06-26 09:54 UTC, Gracechung-sw commented
Dockerfile도 
```yml
# Production Dockerfile
# This Dockerfile allows to build a production Docker image of the NestJS application.
# It can be used to Amazon ECS task definitions to launch containers.

FROM node:16.5-alpine as builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY .npmrc ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .
RUN pnpm run build && pnpm prune --production

# ---

FROM node:16.5-alpine

ENV NODE_ENV production

WORKDIR /app
COPY --from=builder --chown=node:node /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD [ "node", "dist/main" ]

```

이런 식으로 바꿔주면 어떨까욥

2022-06-26 09:55 UTC, Gracechung-sw requested changes
Dockerfile도 
```yml
# Production Dockerfile
# This Dockerfile allows to build a production Docker image of the NestJS application.
# It can be used to Amazon ECS task definitions to launch containers.

FROM node:16.5-alpine as builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY .npmrc ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .
RUN pnpm run build && pnpm prune --production

# ---

FROM node:16.5-alpine

ENV NODE_ENV production

WORKDIR /app
COPY --from=builder --chown=node:node /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD [ "node", "dist/main" ]

```

이런 식으로 바꿔주면 어떨까욥

2022-06-26 14:53 UTC, Marades commented
@Gracechung-sw 

아이구  dev랑 readme는 건드려놓고 prod버전 dockerfile을 건드릴 생각을 못했네욥..! 올려주신대로 수정해서 다시 커밋했습니다!

2022-06-27 10:52 UTC, Gracechung-sw approved these changes

2022-06-27 10:52 UTC, hyeonjeongchung commented
> @Gracechung-sw
> 
> 아이구 dev랑 readme는 건드려놓고 prod버전 dockerfile을 건드릴 생각을 못했네욥..! 올려주신대로 수정해서 다시 커밋했습니다!

수고하셨습니다!

2022-06-28 17:05 UTC, merged